# Server
server.port=8080

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/password_analyzer_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=#Shreya@22

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect